vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        nosimages:
            uri_prefix: /images/imagesite
            upload_destination: '%kernel.project_dir%/public/images/nosimages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
