vich_uploader:
    db_driver: orm

    mappings:
       nosimages:
           uri_prefix: /images/nosimages
           upload_destination: '%kernel.project_dir%/public/images/nosimages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
